### ISSUE TITLE
OCAPI Connection to Staging

### ISSUE THREAD

**Issue by fishme** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#1] opened 2019-06-18 13:09 UTC
Hi guys,

The deployment to a normal SB was working perfect.
I configured now everything for the deployment to the staging instance. (with certificates etc.)

I get always :-(
host: cert.staging.euXXX.XXXXX.demandware.net

```
Failed to authenticate with OCAPI! 400 - Bad Request!
Response=<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

```
We have the 2FA active for the client organisation. 
This my OCAPI Config data/global

```
{
    "_v": "19.5",
    "clients": [
        {
            "client_id": "MY_SECRECT_CODE",
            "resources": [
                {
                    "resource_id": "/code_versions/*",
                    "methods": ["put", "patch"],
                    "read_attributes": "(**)",
                    "write_attributes": "(**)"
                }
            ]
        }
    ]
}
```

Is there anything else that I have to setup?

**Comment by danechitoaie** [comment] 2019-06-18 13:50
Hmm, that's strange. First time I see this kind of error.
Can you try and make a request to same hostname/url with `curl` or `Postman`? So we can see if the issue is server side or client side.

**Comment by ClaudiuCudla** [comment] 2019-06-18 13:54
Can you try to generate a .p12 and connect with Cyberduck? I recently tried to connect with 2FA on a staging environment and there's a handshake failure, for which I asked SFCC about and still waiting for a reply.

**Comment by temoedjin** [comment] 2019-06-19 09:33
Hello there. I am answering for @fishme 

Using curl connecting to the host actually gives the same error.
So I guess this is a server problem? Your wisdom much appreciated.

```
curl --cacert cert.staging.xx.xxx.demandware.net_01.crt -E ./file.crt.pem --key ./file.key.pem https://cert.staging.xx.xxx.demandware.net
```
gives 

```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by ClaudiuCudla** [comment] 2019-06-19 09:35
What if you visit the url directly in the browser?
Does https://cert.staging.euXXX.XXXdemandware.net/on/demandware.servlet/webdav/Sites/Cartridges
gives you the option to request for auth after selecting the certificate?

**Comment by temoedjin** [comment] 2019-06-19 09:46
Hi @ClaudiuCudla ,

In the browser we get this :( No option to do anything with auth

```
Your connection is not private
Attackers might be trying to steal your information from cert.staging.xx.xxx.demandware.net (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
```

**Comment by ClaudiuCudla** [comment] 2019-06-19 09:48
You should have been prompted to select your local certificate (.p12 installed) at least or something. It does seem something related to SFCC and unfortunately I haven't had this issue. I suggest a ticket for this on their end to see what's wrong.

**Comment by temoedjin** [comment] 2019-06-19 09:52
Thanks @ClaudiuCudla we'll do that.

**Comment by danechitoaie** [comment] 2019-06-19 09:52
@temoedjin Yes, if it doesn't work with `curl` also I would say it's a server side issue. Maybe a problem with how SFCC configured the server. We now have two different unrelated tools having the same issue so we can assume it's not on our side. I think you might need to create a support ticket with them so investigate the issue on their end.

**Comment by danechitoaie** [comment] 2019-06-25 08:38
@temoedjin @fishme Did you manage to fix the issue? Anything I can help with or we can close the issue?

**Comment by danechitoaie** [comment] 2019-07-18 22:18
Closing issue. Please reopen if you're still having issues and there's something I can help with.

**Closed as completed by danechitoaie** 2019-07-18 22:18 UTC
